<div class="header indigo lighten-1 padding-2">

	<div class="page-title">

		<button class="btn btn-flat">
			<i class="material-icons">menu</i>
		</button>

		<h1 class="title">
			<i class="material-icons">peoples</i>
			Parceiros
		</h1>

	</div>

	<div class="page-search">
		<div class="search-wrapper z-depth-1">
			<div class="search">
				<i class="material-icons">search</i>
				<input type="search" placeholder="Pesquisar Parceiro" class="" value="<?= $filtro; ?>">
			</div>
		</div>
	</div>

</div>

<div class="page container no-padding">

	<div class="content">

		<div class="sidebar">

			<div class="sidebar-content">

				<div class="sidebar-header">
					<button id="adicionar" class="btn btn-large mb-10 green waves-effect waves-light"
						data-tooltip="Adicionar Parceiro" data-position="right">
						Adicionar Parceiro
					</button>
				</div>

				<div class="sidebar-body">

					<div class="card no-margin">

						<div class="card-content no-padding">

							<div class="card-header">

								<h5>
									Categorias
								</h5>

								<button
									class="btn btn-flat btn-floating transparent waves-effect float-right dropdown-trigger"
									data-target="order-by">
									<i class="material-icons right grey-text text-darken-4">keyboard_arrow_down</i>
								</button>

								<ul id="order-by" class="dropdown-content" tabindex="0" style="width: 100%;">
									<li tabindex="0">
										<a href="javascript:void(0);" class="waves-effect modal-trigger"
											data-toggle="modal" data-target="modal-form-categoria"
											data-tooltip="Adicionar Categoria" data-type="html">
											<i class="material-icons">add</i>
											Categoria</a>
									</li>
								</ul>

							</div>

							<div class="card-body">

								<ul id="listar-categorias">
									<li>
										<a href="#categorias/*" class="active lighten-1 waves-effect">
											Todas
										</a>
									</li>
									<?php foreach( $categorias -> result() as $categoria) : ?>
									<li>
										<a href="#categorias/<?= $categoria -> id; ?>" class="lighten-1 waves-effect">
											<?= $categoria -> categoria; ?>
										</a>
									</li>
									<?php endforeach; ?>
								</ul>

							</div>

						</div>

					</div>

				</div>

			</div>

		</div>

		<div class="container-right">

			<div id="page-list" class="card">

				<div class="card-content no-padding">

					<input type="hidden" name="_method" value="delete">

					<div id="scroll-table" class="table striped" data-url="<?= base_url(); ?>parceiros">

						<div class="table-header">

							<div class="table-row">

								<div class="table-col checkbox center-align small-cell" data-orderable="false">

									<label>
										<input type="checkbox" class="" id="check-all">
										<span></span>
									</label>

								</div>

								<div class="table-col table-actions" data-orderable="false">
									<div class="buttons">
										<button class="btn-flat btn-floating transparent waves-effect">
											<i class="material-icons grey-text">delete</i>
										</button>
										<button class="btn-flat btn-floating transparent waves-effect">
											<i class="material-icons grey-text">add</i>
										</button>
										<button class="btn-flat btn-floating transparent waves-effect">
											<i class="material-icons grey-text">delete</i>
										</button>
										<div class="divider vertical"></div>
										<button class="btn-flat btn-floating transparent waves-effect">
											<i class="material-icons grey-text">delete</i>
										</button>
									</div>
								</div>
								<div class="table-col asc">
									Nome
								</div>
								<div class="table-col">
									Categoria
								</div>

							</div>

						</div>

						<div class="table-body">

							<div class="table-body--content">

								<?php if ( $parceiros -> numRows() > 0 ) : ?>

								<?php foreach($parceiros -> result() as $parceiro) : ?>
								<div class="table-row waves-effect">

									<div class="table-col checkbox center-align small-cell">

										<label class="waves-effect btn-floating z-depth-2">
											<input type="checkbox" name="id[]" class="trash">
											<i class="material-icons">check</i>
											<img src="<?= site_url() . $parceiro -> logomarca; ?>" class="" alt="">
										</label>

									</div>
									<div class="table-col">
										<?= $parceiro -> nome; ?>
									</div>
									<div class="table-col">
										<?= $parceiro -> categoria ?>
									</div>

								</div>
								<?php endforeach; ?>

								<?php else : ?>

								<div class="table-row no-data" style="position: absolute; height: 100%; width: 100%;">

									<div class="table-col center-align">
										<span>Nenhum registro encontrado.</span>
									</div>

								</div>

								<?php endif; ?>

							</div>

						</div>

					</div>

				</div>

			</div>

			<div id="page-form" class="card" style="display: none;">

				<form action="<?= base_url(); ?>parceiros" autocomplete="off">

					<div class="card-content">

						<div class="card-header">

							<button id="back-list" class="btn btn-flat btn-floating transparent waves-effect left">
								<i class="material-icons black-text">keyboard_arrow_left</i>
							</button>

							<h5>
								Novo Parceiro
							</h5>

						</div>

						<div class="row">


							<div class="col s6 l7 offset-l2">

								<div class="row">
									<!-- nome -->
									<div class="col s6 l12">
										<div class="input-field inline grey lighten-4">
											<i class="prefix material-icons black-text">people</i>
											<i class="sufix material-icons black-text">people</i>
											<label for="nome" class="<?= isset($row) ? '' : null; ?> grey-text">
												Nome
											</label>
											<input type="text" name="nome"
												value="<?= isset($row) ? $row -> getNome() : null; ?>" id="nome">
										</div>
									</div>
									<!--/nome -->
								</div>

								<div class="row">


									<!-- cep -->
									<div class="col s3">
										<div class="input-field inline grey lighten-4">
											<input type="text" name="cep"
												value="<?= isset($row) ? $row -> getNome() : null; ?>" id="cep">
											<label for="cep" class="<?= isset($row) ? '' : null; ?> grey-text">
												CEP
											</label>
										</div>
									</div>
									<!--/cep -->

									<!-- logradouro -->
									<div class="col s6">
										<div class="input-field inline grey lighten-4">
											<input type="text" name="logradouro"
												value="<?= isset($row) ? $row -> getNome() : null; ?>" id="logradouro">
											<label for="logradouro" class="<?= isset($row) ? '' : null; ?> grey-text">
												Endereço
											</label>
										</div>
									</div>
									<!--/logradouro -->

									<!-- numero -->
									<div class="col s3">
										<div class="input-field inline grey lighten-4">
											<input type="text" name="numero"
												value="<?= isset($row) ? $row -> getNome() : null; ?>" id="numero">
											<label for="numero" class="<?= isset($row) ? '' : null; ?> grey-text">
												Número
											</label>
										</div>
									</div>
									<!--/numero -->

								</div>

								<div class="row">

									<!-- bairro -->
									<div class="col s6">
										<div class="input-field inline grey lighten-4">
											<input type="text" name="bairro"
												value="<?= isset($row) ? $row -> getNome() : null; ?>" id="bairro">
											<label for="bairro" class="<?= isset($row) ? '' : null; ?> grey-text">
												Bairro
											</label>
										</div>
									</div>
									<!--/logradouro -->

									<!-- complemento -->
									<div class="col s6">
										<div class="input-field inline grey lighten-4">
											<input type="text" name="complemento"
												value="<?= isset($row) ? $row -> getNome() : null; ?>" id="complemento">
											<label for="complemento" class="<?= isset($row) ? '' : null; ?> grey-text">
												Complemento
											</label>
										</div>
									</div>
									<!--/logradouro -->

								</div>

								<div class="row">

									<!-- cidade -->
									<div class="col s10">
										<div class="input-field inline grey lighten-4">
											<input type="text" name="cidade"
												value="<?= isset($row) ? $row -> getNome() : null; ?>" id="cidade">
											<label for="cep" class="<?= isset($row) ? '' : null; ?> grey-text">
												Cidade
											</label>
										</div>
									</div>
									<!--/cidade -->

									<!-- estado -->
									<div class="col s2">
										<div class="input-field inline grey lighten-4">
											<input type="text" name="estado"
												value="<?= isset($row) ? $row -> getNome() : null; ?>" id="estado">
											<label for="estado" class="<?= isset($row) ? '' : null; ?> grey-text">
												UF
											</label>
										</div>
									</div>
									<!--/estado -->

									<div class="col s12">
										<div class="input-field border-0">
											<button class="btn btn-large border-round teal waves-effect">
												<i class="material-icons left">save</i> salvar
											</button>
										</div>
									</div>

								</div>

							</div>

						</div>

					</div>

				</form>

			</div>

		</div>

	</div>

</div>

<div id="modal-form-categoria" class="modal"></div>